#include<iostream>
using namespace std;
main(){

string moviename;
float adultticket;
float childticket;
int adtixsold;
int chtixsold;

cout << "Enter the movie name: ";
cin >> moviename;

cout << "Enter the adult ticket price: $";
cin >> adultticket;
cout << "Enter the child ticket price: $";
cin >> childticket;

cout << "Enter no of adult tickets sold: ";
cin >> adtixsold;
cout << "Enter no of child tickets sold: ";
cin >> chtixsold;

float percentagedonated;
cout << "Enter the percentage of amount donated to charity: ";
cin >> percentagedonated;

float totalamount;
totalamount = (adultticket*adtixsold)+(childticket*chtixsold);
cout << "Total amount generated by the tickets is: $" << totalamount <<endl;

float amountdonated;
amountdonated = totalamount*(percentagedonated/100);
cout << "Amount donated to charity(" << percentagedonated << "%) : $" << amountdonated <<endl;

float remainingamount;
remainingamount = totalamount-amountdonated;
cout << "Remaining amount after donation: $" << remainingamount <<endl;











}